[Basic Data Exploration](#basic-explor)

[Bivariate analysis](#bivar)

## Course Structure

1. Module 0 - Native Data Types in Python
2. Module 1 - Intro to Pandas library & Basis Dataframe attributes
3. Module 2 - Common Data manipulation tasks using Pandas
4. Module 3 - Loops and Functions 
5. Module 4 - Visualization
6. Module 5 - Other miscellaneous topics

# Basic data types

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
x = [1,"b",3]

In [ ]:
x[1]

In [ ]:
student_dict = {"s_1":["IBM","TCS"],"s_2" :["HP"], "s_3":["INFOSYS","WIPRO"]}

In [ ]:
[val for k,val in student_dict.items()]

In [ ]:
x = ["abe",1,"c"]

In [ ]:
dist_ex = {"S1":["HCL","TCS"],"S2":["Benz"]}

In [ ]:
for k,v in dist_ex.items():
    if k == "S1":
        print(k)

In [ ]:
x.append("h")

In [ ]:
x

In [ ]:
tup_ex = (1,2,3,1)

In [ ]:
!pip install pandas

In [ ]:
list_ex = [1,2,3]
dist_ex = {"Age":25,"Weight":70}

tup_ex = (1,2,3,1)

In [ ]:
from pandas import read_csv

In [1]:
# read the data
import pandas as pd
import numpy as np
df = pd.read_csv("Uber Drives 2016.csv")

In [2]:
df

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
...,...,...,...,...,...,...,...
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

# Key Modules

1. Basic Dataframe operations
2. Common data manipulation tasks
3. Loops and Functions

## Basic dataframe operations

In [3]:
df.head()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [4]:
df.shape

(1156, 7)

In [5]:
hasattr(df,"head")
callable(getattr(df,"head"))

True

In [6]:
df.tail()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [7]:
df.dtypes

START_DATE*     object
END_DATE*       object
CATEGORY*       object
START*          object
STOP*           object
MILES*         float64
PURPOSE*        object
dtype: object

### Changing data types

In [8]:
temp = pd.DataFrame({"A":["1","2","3"],"B":[11,12,13],"C":["12-06-2012","13-06-2015","15-06-2017"]})

In [9]:
temp.dtypes

A    object
B     int64
C    object
dtype: object

In [10]:
temp["C"] = pd.to_datetime(temp["C"])

In [11]:
temp["A"] = pd.to_numeric(temp["A"])

In [12]:
temp.dtypes

A             int64
B             int64
C    datetime64[ns]
dtype: object

In [13]:

temp["A"] = temp["A"].astype(str)

In [14]:
temp.dtypes

A            object
B             int64
C    datetime64[ns]
dtype: object

In [15]:
# convert data to datetime format
pd.to_datetime(df["START_DATE*"],format='%m/%d/%Y %H:%M')
# Available time formats: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

ValueError: time data 'Totals' does not match format '%m/%d/%Y %H:%M' (match)

### Dataset summarization methods

In [16]:
df.describe(include="all")

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
count,1156,1155,1155,1155,1155,1156.000000,653
unique,1155,1154,2,177,188,NaN,10
top,6/28/2016 23:34,6/28/2016 23:59,Business,Cary,Cary,NaN,Meeting
freq,2,2,1078,201,203,NaN,187
mean,NaN,NaN,NaN,NaN,NaN,21.115398,NaN
std,NaN,NaN,NaN,NaN,NaN,359.299007,NaN
min,NaN,NaN,NaN,NaN,NaN,0.500000,NaN
25%,NaN,NaN,NaN,NaN,NaN,2.900000,NaN
50%,NaN,NaN,NaN,NaN,NaN,6.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,10.400000,NaN
max,NaN,NaN,NaN,NaN,NaN,12204.700000,NaN

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   START_DATE*  1156 non-null   object
 1   END_DATE*    1155 non-null   object
 2   CATEGORY*    1155 non-null   object
 3   START*       1155 non-null   object
 4   STOP*        1155 non-null   object
 5   MILES*       1156 non-null   float64
 6   PURPOSE*     653 non-null    object
dtypes: float64(1), object(6)
memory usage: 63.3+ KB

In [18]:
# count of unique start locations
df["START*"].value_counts().head()

Cary                201
Unknown Location    148
Morrisville          85
Whitebridge          68
Islamabad            57
Name: START*, dtype: int64

## Common data manipulation tasks

5 verbs of data manipulation

1. Selecting/Indexing
2. Filtering
3. Sorting
4. Mutating/ Conditionally adding columns
5. Groupby/Summarize

### Select/Indexing

In [19]:
df.iloc[0:5,0:5]

      START_DATE*       END_DATE* CATEGORY*       START*            STOP*
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach

In [20]:
## Positional Indexing
df.iloc[0:4,[0,1]]

      START_DATE*       END_DATE*
0  1/1/2016 21:11  1/1/2016 21:17
1   1/2/2016 1:25   1/2/2016 1:37
2  1/2/2016 20:25  1/2/2016 20:38
3  1/5/2016 17:31  1/5/2016 17:45

In [21]:
df.iloc[0:4,0:3]

      START_DATE*       END_DATE* CATEGORY*
0  1/1/2016 21:11  1/1/2016 21:17  Business
1   1/2/2016 1:25   1/2/2016 1:37  Business
2  1/2/2016 20:25  1/2/2016 20:38  Business
3  1/5/2016 17:31  1/5/2016 17:45  Business

In [22]:
# label based indexing
df.loc[:,["START_DATE*","CATEGORY*"]].head()

      START_DATE* CATEGORY*
0  1/1/2016 21:11  Business
1   1/2/2016 1:25  Business
2  1/2/2016 20:25  Business
3  1/5/2016 17:31  Business
4  1/6/2016 14:42  Business

### In Class assignment

Extract first 5 rows and columns START_DATE* and MILES*

In [23]:
df.loc[0:5,["START_DATE*","MILES*"]]

      START_DATE*  MILES*
0  1/1/2016 21:11     5.1
1   1/2/2016 1:25     5.0
2  1/2/2016 20:25     4.8
3  1/5/2016 17:31     4.7
4  1/6/2016 14:42    63.7
5  1/6/2016 17:15     4.3

### Filtering

In [24]:
df2 = df.loc[df["MILES*"] > 10,["MILES*"]]
df2

       MILES*
4        63.7
9        16.5
10       10.8
22       15.1
23       11.2
...       ...
1134     11.9
1144     12.9
1152     16.2
1154     48.2
1155  12204.7

[316 rows x 1 columns]

In [ ]:
df3 = df2.loc[0:3]

In [ ]:
# find out all rides greater than 10 miles
df.loc[df["MILES*"] > 10].head()

In [ ]:
# Find out all rides to Cary
df.loc[df["START*"]=="Cary",["MILES*"]].head()

In [ ]:
# Find out all rides to Cary & Morrisville          
df[df["START*"].isin(["Cary","Morrisville"])].shape

In [ ]:
# Find out all rides to Cary & Morrisville          
df.loc[df["START*"].isin(["Cary","Morrisville"])].shape

In [ ]:
df.loc[~df["START*"].isin(["Cary","Morrisville"])].shape

#### In class assignment

1. Find all trips with distance > 10 miles and originating from Cary and Morris.

2. Extract top 3 rows from the filtered dataset

### Sorting

In [41]:
df.sort_values(by=["MILES*"],ascending=False).head(5)

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN
269,3/25/2016 16:52,3/25/2016 22:22,Business,Latta,Jacksonville,310.3,Customer Visit
270,3/25/2016 22:54,3/26/2016 1:39,Business,Jacksonville,Kissimmee,201.0,Meeting
881,10/30/2016 15:22,10/30/2016 18:23,Business,Asheville,Mebane,195.9,NaN
776,9/27/2016 21:01,9/28/2016 2:37,Business,Unknown Location,Unknown Location,195.6,NaN

In [42]:
df.sort_values(by=["START*", "MILES*"],ascending=[True,False]).head(5)

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
906,11/4/2016 21:04,11/4/2016 21:20,Business,Agnew,Cory,4.3,NaN
911,11/6/2016 10:50,11/6/2016 11:04,Business,Agnew,Renaissance,2.4,NaN
908,11/5/2016 8:34,11/5/2016 8:43,Business,Agnew,Renaissance,2.2,NaN
910,11/5/2016 19:20,11/5/2016 19:28,Business,Agnew,Agnew,2.2,NaN
879,10/30/2016 12:58,10/30/2016 13:18,Business,Almond,Bryson City,15.2,NaN

### Conditionally adding columns

In [ ]:
import numpy as np
df["miles_cat"] = np.where(df["MILES*"] > 5,"Long Trip","Short Trip")

In [ ]:
df.head()

In [ ]:
df["miles_cat"].value_counts()

In [ ]:
df.loc[df["MILES*"] > 5].shape

## In class Assignment

Create a new column with the following condition:

a) > 10 - Long Trip

b) 5 - 10  - Medium

c) < 5 - Short Trip

### Groupby Summarize

In [25]:
# for each start loc find the mean distance travelled
df.groupby("START*")["MILES*"].agg("mean").head()

START*
Agnew         2.775000
Almond       15.200000
Apex          5.341176
Arabi        17.000000
Arlington     4.900000
Name: MILES*, dtype: float64

In [43]:
df = df.iloc[:-1,:]
df.tail()
df["START_DATE*"]=pd.to_datetime(df["START_DATE*"])
df.dtypes

#res = df.groupby("START*").agg({"MILES*": ["mean","max","min"] , "START_DATE*": ["max","min"]})
#res
df.groupby("START*").agg({"MILES*":("mean")})

                     MILES*
START*
Agnew              2.775000
Almond            15.200000
Apex               5.341176
Arabi             17.000000
Arlington          4.900000
...                     ...
West University    2.200000
Weston             4.000000
Westpark Place     2.182353
Whitebridge        4.020588
Winston Salem    133.600000

[175 rows x 1 columns]

In [ ]:
# for each start loc find the mean & the total dist travelled
df.groupby("START*").agg(["mean","sum"]).head()

### In class assignment

Find most recent & the earliest travelled date and mean distance traveled for each start city

## Loops and Function

In [44]:
# Basic for loop
res = []
temp = [1,2,3,4]
for i in temp:
    res.append(i*i)
res

[1, 4, 9, 16]

In [45]:
# List comprehension way

[x*x for x in temp]

[1, 4, 9, 16]

In [49]:
store_sales = pd.read_csv("store_sales.csv")

In [50]:
store_sales.head()

,store_id,city,Jan,Feb,Mar,Apr,May,Jun,July,Aug,Sep,Oct,Nov,Dec
0,S_1,Texas,8,20,13,21,17,20,24,17,16,9,7,6
1,S_2,California,12,19,15,15,11,19,7,15,10,11,21,19
2,S_3,California,16,16,14,19,23,6,13,13,15,14,24,8
3,S_4,Texas,8,18,13,10,14,14,6,8,8,18,7,11
4,S_5,Texas,19,5,24,9,5,24,10,5,24,15,6,13

In [59]:
store_sales["Jan"].mean()

14.46

In [ ]:
# find out avg sales for each month
# find out avg sales for each store

In [ ]:
def bonus_func(sales_numbers):
    return ["Eligible" if x > 15 else "Not Eligible" for x in sales_numbers]

In [ ]:
bonus_func([12,23,56])

In [ ]:
store_sales.iloc[:,2:].apply(bonus_func).head()

In [ ]:
store_sales.iloc[:,2:].apply(lambda sales_numbers: ["Eligible" if x > 15 else "Not Eligible" for x in sales_numbers]).head()

In [ ]:
store_sales.columns

In [ ]:
store_sales.groupby("city").agg("mean")

### Assignments

1) Find mean quarterly sales by store

2) Find the month with highest sales for each store

## Other/Miscellaneous topics

### Missing value treatment

In [ ]:
df.isnull().sum()

In [ ]:
## Count missing values
df.isnull().sum()

In [ ]:
# Fill NA with most common values
df["PURPOSE*"].value_counts()

In [ ]:
df = df.fillna({"PURPOSE*":"Meeting"})

In [ ]:
df["PURPOSE*"].value_counts()

### Matrix operations use case

### Example 1 - compute month on month growth in sales

In [ ]:
store_sales.head()

In [ ]:
sales_mat = np.array(store_sales.iloc[:,2:])

In [ ]:
sales_mat

In [ ]:
sales_mat_lag = sales_mat[:,1:]
sales_mat_lag

In [ ]:
sales_mat_lag = sales_mat[:,1:]
sales_mat_lag = np.c_[sales_mat_lag,np.zeros(100)]

In [ ]:
sales_diff = sales_mat_lag - sales_mat

In [ ]:
perct_change = pd.DataFrame(sales_diff/sales_mat)

In [ ]:
perct_change.head()

### Example 1 - compute net revenue

In [ ]:
profit_mat = np.random.uniform(low=0.05, high=0.25, size=(100,12))

In [ ]:
## Find total annual profit for each store
profit_mat = profit_mat.transpose()

In [ ]:
profit_mat.shape

In [ ]:
prof_matrix = np.dot(sales_mat,profit_mat)

In [ ]:
prof_matrix.shape