In [16]:
import numpy as np
import pandas as pd

In [17]:
URL=""
data=pd.read_csv()
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [18]:
from sklearn import preprocessing
label = preprocessing.LabelEncoder()
data['sex'] = label.fit_transform(data['sex'])
data['smoker'] = label.fit_transform(data['smoker'])
data.head()

   age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [19]:
features=["age","sex","bmi","children","smoker"]
x = data[features]
y = data["charges"]

In [20]:
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y = train_test_split(x,y)

In [21]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(random_state = 0)
regressor.fit(train_x, train_y)

RandomForestRegressor(random_state=0)

In [24]:
regressor.predict([[19,0,27.900,0,1]])

array([17070.703299])

In [25]:
regressor.predict(x[:5])

array([17070.703299 ,  2555.881824 ,  4831.1772507, 15893.9187216,
        4033.4416453])

In [22]:
prediction = regressor.predict(test_x)

In [23]:
from sklearn.metrics import mean_absolute_error
errors = (mean_absolute_error(test_y,prediction)) 

print(errors)

2750.783050824826