In [20]:
import pandas as pd

In [21]:
data = pd.read_csv('/Users/aviral/Documents/programming/datas/student2.csv')
data.head()

,Database Fundamentals,Computer Architecture,Distributed Computing Systems,Cyber Security,Networking,Software Development,Programming Skills,Project Management,Computer Forensics Fundamentals,Technical Communication,AI ML,Software Engineering,Business Analysis,Communication skills,Data Science,Troubleshooting skills,Graphics Designing,Role
0,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator
1,9,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator
2,9,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator
3,9,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator
4,9,6,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator

In [22]:
features = ['Database Fundamentals','Computer Architecture','Distributed Computing Systems','Cyber Security','Networking','Software Development','Programming Skills','Project Management','Computer Forensics Fundamentals','Technical Communication','AI ML','Software Engineering','Business Analysis','Communication skills','Data Science','Troubleshooting skills','Graphics Designing']
x = data[features]
y = data['Role']

In [23]:
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y = train_test_split(x,y)

In [24]:
from lazypredict.Supervised import LazyClassifier

model = LazyClassifier()
models, predictions = model.fit(train_x,test_x,train_y,test_y)
models.head(60)

 34%|███▍      | 10/29 [00:03<00:05,  3.66it/s]

In [ ]:
from sklearn.svm import SVC

SVM = SVC()
SVM.fit(train_x,train_y)

SVC()

In [ ]:
data.head()

,Database Fundamentals,Computer Architecture,Distributed Computing Systems,Cyber Security,Networking,Software Development,Programming Skills,Project Management,Computer Forensics Fundamentals,Technical Communication,AI ML,Software Engineering,Business Analysis,Communication skills,Data Science,Troubleshooting skills,Graphics Designing,Role
0,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator
1,9,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator
2,9,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator
3,9,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator
4,9,6,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Database Administrator

In [ ]:
SVM.predict([[8,1,1,4,1,1,6,5,1,7,9,1,6,7,9,1,1]])

array(['AI ML Specialist'], dtype=object)

In [ ]:
prediction = SVM.predict(test_x)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(test_y, prediction)

0.9995642701525055

In [ ]:
import pickle

In [ ]:
with open('model2_pkl', 'wb') as files:
    pickle.dump(SVM, files)